### ISSUE TITLE
Support HUD-only display & map-only display

### ISSUE THREAD

**Issue by wiseman** [wiseman/mavelous#1]
It would be nice to be able to run a HUD/PFD in one browser while using a map/mission editor in another.

**Comment by pchickey** [comment]
I will implement this as part of the bootstrap-ui changes, currently in progress.

Currently bootstrap-ui is capable of moving the PFD to the left and right edges of the screen. It should be able to move place it in any of the four corners shortly. I'll also implement options in there to hide and maximize the size.

**Comment by osmogr** [comment]
What pchickey said! PFD/HUD without map (Or map in a small window), MAP Screen, and a Status Screen which could show details of the MAV.

**Comment by pchickey** [comment]
This feature is almost done - I just need to find an hour or two put the
finishing touches on it. Thanks for the feedback.

On Thu, Aug 2, 2012 at 10:46 PM, osmogr <
reply@reply.github.com

**Comment by pchickey** [comment]
I pushed a handful of commits tonight that allow three display modes - Overview (current layout of PFD + map), PFD (fullscreen PFD), and Map (no PFD). I'll add an option that allows the user to specify the size of the PFD in overview soon.

**Comment by osmogr** [comment]
Looks Mavelous!  Was able to test a bit last night and this morning on the ground.   Using chromium browser on Ubuntu 12.04.   

No screen issues with new options.  Was able to switch between overview, Pfd and map without any screen size issues.
