### ISSUE TITLE
Screen is useless on iPhone

### ISSUE THREAD

**Issue by skelly** [wiseman/mavelous#12]
I posted a screenshot to the mailing list of mavelous running on Safari on iOS 6, the map is mostly not viewable, and some controls are out of reach. The settings popup works great though.

**Comment by pchickey** [comment]
Sam - could you please send a screenshot of how this looks on the iPhone now?

I know fullscreen PFD doesn't quite render as big as it should yet. I'm working on fixing that now...

**Comment by skelly** [comment]
Here's a couple of screenshots taken just now.

![](http://cl.ly/image/160A1o1Q0V1I/Photo%20Aug%2006,%2011%2024%2017%20AM.png)

![](http://cl.ly/image/350Q3z2G1O30/Photo%20Aug%2006,%2011%2024%2003%20AM.png)

Sorry for the delay, didn't have any of this set up on my home computer.

**Comment by pchickey** [comment]
Thanks for the screenshots! No worries about the delay.

Those look pretty terrible. I expected the guide altitude display to be hidden when the rest of the PFD is. Guess I've still got some work to do.

For the portrait view: did you load the page as landscape and then rotate (this is bad and I don't know how to deal with it) or reload in portrait mode? When you load in portrait mode I think the screen should detect its not big enough to show the Overview and go to either PFD or Map.

**Comment by skelly** [comment]
I loaded the page only once, started in portrait then rotated to landscape without refreshing.

-Sam

**Comment by wiseman** [comment]
The UI is much more usable on the iPhone now, see https://groups.google.com/forum/?fromgroups=#!topic/mavelous/Eq__BpVYI3s for a screenshot.  It looks pretty much the same in portrait and landscape mode.

Remaining issues:
- Sometimes the flight controls/gps/communications status/battery buttons try to open links, prompting you whether you want to open a new window.
- We need a battery icon.  The current icon is a flame, for no good reason.
- Some flight mode labels cause the flight mode/controls button to get too big and break the layout a little.

**Comment by wiseman** [comment]
Screenshot:

![](http://i.imgur.com/gq4F2.jpg)
