### ISSUE TITLE
Cache maps for offline

### ISSUE THREAD

**Issue by osmogr** [wiseman/mavelous#13]
Feature Request

Cache maps for offline use.

**Comment by wiseman** [comment]
I think Google and Bing forbid caching in their terms of service, but there are other sources of map tiles that allow it, so Mavelous should support it.

**Comment by osmogr** [comment]
Agreed.  Some sort of topo map source would be nice too.

**Comment by scastillop11178** [comment]
Anyone developed any code for static maps? I think this could be possible, mission planner does with google.

**Comment by pchickey** [comment]
At this time we won't be adding caching code to the existing bing satellite imagery, as it is against bing's TOS.

**Comment by scastillop11178** [comment]
ok, thank you for the information
