### ISSUE TITLE
Missing Modules in distribution?

### ISSUE THREAD

**Issue by overlordsc** [wiseman/mavelous#15]
Traceback (most recent call last):
  File "mavproxy.py", line 1602, in <module>
    import mavutil, mavwp
ImportError: No module named mavutil

**Comment by wiseman** [comment]
Yeah, unfortunately at the moment getting mavelous running is about equivalent to getting mavlink running, and that is a little bit tricky/non-standard.

My plan is to submit patches to the maintainers of mavlink and mavelous that would make it possible to install them using standard python tools, and then mavelous would just be another module, but until then I think you just need to checkout the mavlink repository next to marvelous.

That is, if mavelous is in your ~/src directory, do this:

```
cd ~/src
git clone git@github.com:mavlink/mavlink.git
```

**Comment by overlordsc** [comment]
Much Appreciated
