### ISSUE TITLE
Change to default altitude

### ISSUE THREAD

**Issue by scastillop11178** [wiseman/mavelous#20]
Hi!

I would like to change default altitude from 20m to 100m.  I think only I need to make this change in modules/lib/mmap_app/index.html:       

input id="guidealt-input" type="range" value="20" min="0" max="200"

to

input id="guidealt-input" type="range" value="100" min="0" max="200"

But I would like to be sure. Is that ok?

Thank you!

**Comment by pchickey** [comment]
Hi Scastillop,
Unfortunately that won't work for you. To separate the guided mode implementation from the presentation, the guide mode altitude slider element is hooked to a backbone GuideModel using a GuideAltitudeView. The default altitude is always returned as 20m by the defaults method when a new GuideModel is created. You can find this implementation in scripts/guidemodel.js:8 .
Pat

**Comment by scastillop11178** [comment]
Thank you Pat.

That is what I am looking for, change default altitude to be returned 100 instead of 20m. I have made changes to guidemodel.js:

defaults: function() {
      return {
        alt: 100,
        lat: null,
        lon: null
      };
    },

And now I get 100m when I load web page.

Thank you!

Do you know if it is possible and easy to cache maps and make mavelous working with maps cached? I know mission planner does.

**Comment by wiseman** [comment]
We'd like to add tile caching for sure, and randym's patch (
https://github.com/wiseman/mavelous/pull/19) may help us get there.

One issue to be aware of is that there is no good source of aerial imagery
with a license that allows offline caching (as far as I know Mission
Planner is violating Bing's and Google's terms of service).

It looks like Open Aerial Map is one effort to develop open imagery, but
I'm not sure what its status is.  An alternative might be Stamen's terrain
map, but it is US-only:
http://mike.teczno.com/notes/osm-us-terrain-layer/foreground.html

John

**Comment by scastillop11178** [comment]
OK, I didn't think about violating terms.

Thanks.
