### ISSUE TITLE
Question about flight.log file

### ISSUE THREAD

**Issue by pgiacalo** [wiseman/mavelous#24]
Hi guys,

I'm wondering how to read the mavelous flight.log file. After a flight today, I was wondering what the log would show as far as lost links, etc. But when I open the log file in a text editor is contained gibberish. 

Thanks,
Phil

**Comment by pchickey** [comment]
That's a MAVProxy log - I believe it is mavlink packets in their binary
(wire) format. There is a little bit of info on the Mavproxy wiki page.

http://www.qgroundcontrol.org/mavlink/mavproxy_startpage#othersmavlogdump_mavmission_flightmodes_mavextract_gpslock_and_more
