### ISSUE TITLE
How to start mavelous

### ISSUE THREAD

**Issue by pgiacalo** [wiseman/mavelous#44]
Hi Guys,
I just grabbed the latest version of mavelous but the browser isn't launching. I'm starting mavelous on a Mac with the following command. 

python mavproxy.py --master=/dev/tty.usbserial-A4008qH4 --baud=57600 --module mavelous --aircraft=UDB

This command works fine with an older version of mavelous but not with the latest version. Is there a different command I should be using? 

The console output looks like this when it works with the older version. Firefox then opens and displays the aircraft, map, etc. 

bash-3.2$ cd ../../mavelous2/mavelous/
bash-3.2$ python mavproxy.py --master=/dev/cu.usbserial-A4008qH4 --baud=57600 --module mavelous --aircraft=UDB
UDB/logs/2013-01-17/flight2
Logging to UDB/logs/2013-01-17/flight2/flight.log
Loaded module mavelous
GPS lock at 41 meters
height 40
online system 251 component 1
Mode(0x000000d8)> Mode Mode(0x000000d8)
Mode(0x000000d8)> fetching parameters

Here's the console output I see with the latest version. The problem is that Firefox never opens and I see gibberish printed out on the console. 

bash-3.2$ python mavproxy.py --master=/dev/tty.usbserial-A4008qH4 --baud=57600 --module mavelous --aircraft=UDB
UDB/logs/2013-01-17/flight3
Logging to UDB/logs/2013-01-17/flight3/flight.log
Loaded module mavelous
GPS lock at 37 meters
height 40
online system 251 component 1
Mode(0x000000d8)> Mode Mode(0x000000d8)
Mode(0x000000d8)> fetching parameters
Received 63 parameters
Saved 62 parameters to UDB/logs/2013-01-17/flight3/mav.parm
3@=<pO&C^&&K    oK  &^d=4uX]>;b3=UT<K

Thank you in advance for your help with this!

Phil

**Comment by pchickey** [comment]
Hi Phil,

John removed the browser autolaunch a little bit ago. If this is something
you do enjoy having, we could possibly add it as a mavlink console command.

Pat

**Comment by wiseman** [comment]
Right, see https://groups.google.com/d/msg/mavelous/0T3iCRLL-ZU/_tQF2xQ9B1IJ

In the shell running mavelous you should see the message "Mavelous is running at http://localhost:9999".

**Comment by wiseman** [comment]
The reasoning was that it's pretty easy to open the browser window, and opening it automatically probably doesn't make sense if mavelous is running on a router, raspberry pi, phone, etc.

**Comment by pgiacalo** [comment]
Thanks, guys. It's working as designed.
