### ISSUE TITLE
Question about TCP or UDP protocol

### ISSUE THREAD

**Issue by pgiacalo** [wiseman/mavelous#45]
Hi,
In addition to serial data input, does mavelous support telemetry input over TCP or UDP? 
Thanks,
Phil

**Comment by pchickey** [comment]
Its actually Mavproxy which is responsible for accepting mavlink streams as input. The Mavelous server is a module loaded by Mavproxy on startup, and mavlink streams, regardless of their source, are internally plumbed into the Mavelous server.

By default, Mavproxy will attempt to connect to a serial port, but by using the --master command line switch, you can connect to either TCP or UDP streams as well. See the following page for an example in the "Starting Mavproxy" section:
http://qgroundcontrol.org/mavlink/mavproxy_startpage

**Comment by pgiacalo** [comment]
Fantastic, thanks. You're making my day.
