### ISSUE TITLE
broken in late releases of chrome

### ISSUE THREAD

**Issue by pchickey** [wiseman/mavelous#55]
In Chrome 30.0.1556.2 dev:
Uncaught TypeError: Type error kinetic-v4.1.2.min.js:28

Prevents mavelous from working at all (gray screen)

Our kinetic is a few versions behind, 4.5.4 is out currently.

**Comment by pchickey** [comment]
I tried quickly dropping in the latest version but Kinetic 4.5.4 has significant API changes from 4.1.2:
Kinetic.Shape.setDefaultAttrs no longer exists, and if I switch that to call setAttrs (just guessing?) the attribute 'width' causes some other error I don't understand.

So, this will need some actual work to fixup.

**Comment by wiseman** [comment]
Kinetic helped me get started, but I'm not convinced it's still a good tradeoff vs. just using raw canvas.

**Comment by pchickey** [comment]
Thanks for fixing this, John!

On Aug 11, 2013, at 6:23 PM, John Wiseman notifications@github.com wrote:

Kinetic helped me get started, but I'm not convinced it's still a good
tradeoff vs. just using raw canvas.

—
Reply to this email directly or view it on
GitHubhttps://github.com/wiseman/mavelous/issues/55#issuecomment-22469413
.
