### ISSUE TITLE
Split screen between PFD & other control panels, and map

### ISSUE THREAD

**Issue by pchickey** [wiseman/mavelous#7]
The map should only be a portion of the screen, rather than the whole screen. That way the center of the map won't be so close to the edge of the visible map.

This will make it easier to add more controls below the pfd.

**Comment by wiseman** [comment]
That makes sense to me. It'd be nice if the control/PFD panel is collapsable.

**Comment by pchickey** [comment]
I'm in progress on this feature - I started by implementing a Backbone router so that the standard overview, fullscreen pfd, and fullscreen map live at different URLs. I'll hopefully have more to show in a day or two.

**Comment by pchickey** [comment]
I did push the backbone router changes and changes discussed in the previous comment, closing issue #1. I didn't start working on splitting the screen or adding other control panels, though.

**Comment by pchickey** [comment]
Closing this for now to open specific targeted issues.
